version: '3.8'

services:
  dash:
    build: ./dash
    command: gunicorn -b 0.0.0.0:8050 src.app:server
    volumes:
      - ./dash/:/dash/
    ports:
      - 8050:8050
    depends_on:
      - server
  server:
    build: ./server
    command: uvicorn src.app:app --host 0.0.0.0 --port 5000
    volumes:
      - ./server/:/server/
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mcekovic/uts-database
    ports:
      - 5432:5432
